### ISSUE TITLE
`lazy` with mutliple html composition layers appears to cause runtime errors / other odd behavior

### ISSUE THREAD

**Issue by abradley2** [easafe/purescript-flame#49]
Heya! I've been looking into this issue for a bit and it has stumped me, but I've narrowed it down to a reasonably small example.

In this example I have a "counter component" with it's own model, update, view, etc. I wrap the view function of this component in `lazy`. As this component is nested deep in a large application, the `CounterMsg` is lifted up multiple layers via `PageMsg <$> CounterMsg <$> counterView model.counter`.

However, it appears when a lazy node is mapped in this way (specifically two layers upwards),  it will error in response to any event that dispatches a message within that node. In this case I see `v is undefined` (upon further inspection, "v" being the message type passed to `updateCounter`), though in our larger application we see `Failed pattern match`

```
import Flame.Application.NoEffects (mount_)
import Flame.Html.Element (lazy)
import Flame.Html.Element as H
import Flame.Html.Event as E

data CounterMsg
  = Increment Int

type CounterModel
  = { count :: Int }

initCounter :: CounterModel
initCounter = { count: 1 }

updateCounter :: CounterModel -> CounterMsg -> CounterModel
updateCounter model (Increment val) = model { count = model.count + val }

counterView :: CounterModel -> Html CounterMsg
counterView = lazy Nothing counterView_

counterView_ :: CounterModel -> Html CounterMsg
counterView_ model =
  H.div_
    [ H.button
        [ E.onClick $ Increment 1000 ]
        [ H.text $ "Current Value: " <> show model.count ]
    ]

data Msg
  = PageMsg PageMsg

data PageMsg
  = CounterMsg CounterMsg

type Model
  = { counter :: CounterModel }

init :: Model
init = { counter: initCounter }

update :: Model -> Msg -> Model
update model (PageMsg (CounterMsg msg)) = model { counter = updateCounter model.counter msg }

view :: Model -> Html Msg
view model =
  H.div_
    [ PageMsg <$> CounterMsg <$> counterView model.counter
    ]

main :: Effect Unit
main =
  mount_ (QuerySelector "#app")
    { subscribe: []
    , init
    , update
    , view
    }
```

Removing a layer of mapping in the view fixes this problem. If I redefine

```
data Msg
  = PageMsg PageMsg

data PageMsg
  = CounterMsg CounterMsg
```

to

```
data Msg
  = CounterMsg CounterMsg
```

And remove the extraneous mapping then things work as expected

**Comment by easafe** [comment]
Hello @abradley2 ,

Thanks for submitting this issue with a minimal example.  Upon running it, there is indeed something broken. I will look into figuring what exactly as soon as possible.

**Comment by easafe** [comment]
@abradley2 could you please point your version to a50478de01b44d5d83aae15441178ae255484a32? It should be fixed, but right now I don't have any complex projects to test it out on.

**Comment by BusinessTony** [comment]
I tried this out on the isolated example and it did fix the issue. However in our larger application we're still seeing failed pattern matches on the patched version due to messages not mapping correctly. I'm working on isolating the example to figure out what's going on

**Comment by easafe** [comment]
@BusinessTony if the application is open source or if you can put an isolated example online, I can take a look at it to try and help narrow down the problem.

**Comment by BusinessTony** [comment]
@easafe it's not open source unfortunately. However the additional issue I was describing has ceased to turn up after some unrelated refactoring, we've been on a50478d for weeks and not seen any issues and have been using `lazy` successfully. I think we're good 👍

**Comment by easafe** [comment]
Sounds good to me!
